export function adminShell() {
  return String.raw`<!doctype html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>ONYX GROUP — управление заказами</title>
  <style>
    :root{--bg:#050505;--panel:#111;--panel2:#171717;--line:#2a2a2a;--text:#f7f7f8;--muted:#a6a6ad;--accent:#e12a00;--accent2:#ff5a1f;--green:#39d98a;--yellow:#f5c451;--red:#ff6b6b;--radius:20px;color-scheme:dark}
    *{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 10% 0,rgba(225,42,0,.17),transparent 28%),var(--bg);color:var(--text);font:16px/1.45 Inter,system-ui,-apple-system,sans-serif}button,input,select,textarea{font:inherit}button{cursor:pointer}a{color:inherit}.hidden{display:none!important}
    .login-shell{min-height:100vh;display:grid;place-items:center;padding:24px}.login-card{width:min(440px,100%);padding:30px;border:1px solid var(--line);border-radius:28px;background:rgba(17,17,17,.94);box-shadow:0 35px 100px rgba(0,0,0,.55)}.brand{display:flex;align-items:center;gap:12px;margin-bottom:28px}.mark{width:44px;height:44px;border-radius:15px;display:grid;place-items:center;background:linear-gradient(135deg,var(--accent),var(--accent2));font-weight:950}.brand strong{display:block;font-size:1.1rem}.brand span{color:var(--muted);font-size:.82rem;letter-spacing:.08em}.login-card h1{font-size:2rem;letter-spacing:-.05em;margin:0 0 8px}.login-card p{color:var(--muted);margin:0 0 22px}
    .field{display:grid;gap:7px;margin-bottom:14px}.field span{font-size:.88rem;color:#ddd}.field input,.field select,.field textarea,.toolbar input,.toolbar select{width:100%;border:1px solid var(--line);border-radius:14px;background:#0c0c0c;color:var(--text);padding:12px 13px;outline:none}.field textarea{min-height:100px;resize:vertical}.field input:focus,.field select:focus,.field textarea:focus,.toolbar input:focus,.toolbar select:focus{border-color:var(--accent2);box-shadow:0 0 0 3px rgba(255,90,31,.12)}
    .btn{border:1px solid var(--line);border-radius:999px;padding:11px 16px;background:#181818;color:#fff;min-height:44px}.btn:hover{border-color:#444}.btn.primary{border:0;background:linear-gradient(135deg,var(--accent),var(--accent2));font-weight:800}.btn.ghost{background:transparent}.btn.danger{border-color:rgba(255,107,107,.4);color:#ffb0b0}.login-card .btn{width:100%}.error{color:#ffadad;margin-top:12px;min-height:24px}.hint{color:var(--muted);font-size:.88rem}
    .app{min-height:100vh;display:grid;grid-template-columns:240px 1fr}.sidebar{position:sticky;top:0;height:100vh;padding:22px 16px;border-right:1px solid var(--line);background:rgba(8,8,8,.94);display:flex;flex-direction:column}.sidebar .brand{margin:0 4px 26px}.nav{display:grid;gap:7px}.nav button{border:0;border-radius:13px;text-align:left;padding:12px 13px;background:transparent;color:var(--muted)}.nav button:hover,.nav button.active{background:#181818;color:#fff}.account{margin-top:auto;padding:14px 6px 4px;border-top:1px solid var(--line)}.account strong,.account span{display:block}.account span{font-size:.8rem;color:var(--muted);margin:4px 0 12px}
    .main{min-width:0}.topbar{position:sticky;top:0;z-index:5;height:76px;display:flex;align-items:center;justify-content:space-between;padding:0 28px;border-bottom:1px solid var(--line);background:rgba(5,5,5,.86);backdrop-filter:blur(16px)}.topbar h1{font-size:1.15rem;margin:0;letter-spacing:-.03em}.topbar .role{font-size:.82rem;color:var(--muted)}.content{padding:28px;max-width:1500px;margin:0 auto}
    .page-head{display:flex;justify-content:space-between;gap:18px;align-items:end;margin-bottom:22px}.page-head h2{font-size:clamp(1.8rem,4vw,3rem);letter-spacing:-.06em;line-height:1;margin:0 0 7px}.page-head p{margin:0;color:var(--muted)}.grid{display:grid;gap:16px}.stats{grid-template-columns:repeat(5,minmax(0,1fr))}.card{border:1px solid var(--line);border-radius:var(--radius);background:linear-gradient(180deg,#151515,#0d0d0d);padding:18px;min-width:0}.stat span{display:block;color:var(--muted);font-size:.86rem}.stat strong{display:block;font-size:2rem;letter-spacing:-.06em;margin-top:8px}.stat.attention{border-color:rgba(245,196,81,.35)}.stat.problem{border-color:rgba(255,107,107,.35)}
    .toolbar{display:grid;grid-template-columns:minmax(220px,1fr) repeat(3,minmax(140px,220px)) auto;gap:10px;margin-bottom:16px}.table-wrap{overflow:auto;border:1px solid var(--line);border-radius:18px}.table{width:100%;border-collapse:collapse;min-width:850px}.table th,.table td{text-align:left;padding:13px 14px;border-bottom:1px solid var(--line);vertical-align:top}.table th{font-size:.78rem;text-transform:uppercase;letter-spacing:.06em;color:var(--muted);background:#0b0b0b}.table tr:last-child td{border-bottom:0}.table tbody tr{cursor:pointer}.table tbody tr:hover{background:#161616}.code{font-weight:850;white-space:nowrap}.sub{display:block;color:var(--muted);font-size:.84rem;margin-top:3px}.pill{display:inline-flex;align-items:center;padding:5px 9px;border-radius:999px;border:1px solid var(--line);font-size:.8rem;white-space:nowrap}.pill.ok{color:#8ff0bc;border-color:rgba(57,217,138,.3)}.pill.warn{color:#ffe099;border-color:rgba(245,196,81,.3)}.pill.bad{color:#ffadad;border-color:rgba(255,107,107,.3)}.empty{padding:42px;text-align:center;color:var(--muted)}
    dialog{width:min(1100px,calc(100% - 24px));max-height:calc(100vh - 24px);border:1px solid var(--line);border-radius:26px;background:#0b0b0b;color:var(--text);padding:0;box-shadow:0 40px 120px rgba(0,0,0,.75)}dialog::backdrop{background:rgba(0,0,0,.72);backdrop-filter:blur(8px)}.dialog-head{position:sticky;top:0;z-index:2;display:flex;justify-content:space-between;align-items:center;padding:18px 22px;border-bottom:1px solid var(--line);background:rgba(11,11,11,.96)}.dialog-head h2{margin:0;font-size:1.3rem}.dialog-body{padding:22px}.detail-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:16px}.stack{display:grid;gap:16px}.kv{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.kv div{padding:12px;border:1px solid var(--line);border-radius:14px;background:#101010}.kv span{display:block;color:var(--muted);font-size:.8rem}.kv strong{display:block;margin-top:5px;overflow-wrap:anywhere}.card h3{margin:0 0 14px;font-size:1rem}.form-row{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:12px}.item{padding:11px 0;border-bottom:1px solid var(--line)}.item:last-child{border-bottom:0}.item strong,.item span{display:block}.event{padding:10px 0;border-bottom:1px solid var(--line)}.event:last-child{border-bottom:0}.event small{color:var(--muted)}
    .split{display:grid;grid-template-columns:1fr 1fr;gap:16px}.csv{min-height:220px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.notice{padding:13px 15px;border:1px solid rgba(245,196,81,.28);border-radius:14px;background:rgba(245,196,81,.07);color:#ffe7aa}.toast{position:fixed;right:22px;bottom:22px;z-index:20;max-width:420px;padding:13px 16px;border:1px solid var(--line);border-radius:14px;background:#181818;box-shadow:0 20px 70px rgba(0,0,0,.55)}
    @media(max-width:1100px){.stats{grid-template-columns:repeat(2,1fr)}.toolbar{grid-template-columns:1fr 1fr}.toolbar .btn{grid-column:1/-1}.detail-grid,.split{grid-template-columns:1fr}}
    @media(max-width:760px){.app{grid-template-columns:minmax(0,1fr);width:100%;overflow:hidden}.sidebar{position:sticky;top:0;z-index:10;width:100%;max-width:100vw;min-width:0;height:auto;padding:10px;border-right:0;border-bottom:1px solid var(--line);overflow:hidden}.sidebar .brand,.account{display:none}.nav{display:flex;max-width:100%;overflow:auto}.nav button{white-space:nowrap}.topbar{height:60px;padding:0 14px}.content{width:100%;padding:18px 12px}.stats{grid-template-columns:1fr 1fr}.toolbar,.form-row,.kv{grid-template-columns:1fr}.table{min-width:720px}.dialog-body{padding:14px}.page-head{display:block}.page-head .btn{margin-top:12px}}
  </style>
</head>
<body>
  <section id="loginView" class="login-shell">
    <form id="loginForm" class="login-card">
      <div class="brand"><div class="mark">O</div><div><strong>ONYX GROUP</strong><span>OPERATIONS</span></div></div>
      <h1>Вход сотрудников</h1>
      <p>Заказы, поставщики и финансовый контроль.</p>
      <label class="field"><span>Email</span><input id="loginEmail" type="email" autocomplete="username" required></label>
      <label class="field"><span>Пароль</span><input id="loginPassword" type="password" autocomplete="current-password" required></label>
      <button class="btn primary" type="submit">Войти</button>
      <div id="loginError" class="error" role="alert"></div>
    </form>
  </section>

  <section id="appView" class="app hidden">
    <aside class="sidebar">
      <div class="brand"><div class="mark">O</div><div><strong>ONYX GROUP</strong><span>OPERATIONS</span></div></div>
      <nav class="nav" aria-label="Разделы">
        <button data-view="dashboard" class="active">Обзор</button>
        <button data-view="orders">Заказы</button>
        <button data-view="catalog">Товары и поставщики</button>
        <button data-view="finance">Финансы</button>
        <button data-view="automation">Автоматизация</button>
      </nav>
      <div class="account"><strong id="accountName"></strong><span id="accountEmail"></span><button id="logoutButton" class="btn ghost">Выйти</button></div>
    </aside>
    <main class="main">
      <header class="topbar"><h1 id="topbarTitle">Обзор</h1><span id="topbarRole" class="role"></span></header>
      <div id="content" class="content"></div>
    </main>
  </section>

  <dialog id="detailDialog"><div class="dialog-head"><h2 id="dialogTitle">Заказ</h2><button id="closeDialog" class="btn ghost">Закрыть</button></div><div id="dialogBody" class="dialog-body"></div></dialog>
  <div id="toast" class="toast hidden" role="status"></div>

  <script>
    var state={user:null,view:'dashboard',dashboard:null,orders:[],products:[],suppliers:[],offers:[],jobs:[],rules:[],currentOrder:null};
    var labels={
      owner:'Владелец',manager:'Менеджер',finance:'Финансы',
      new:'Новый',checking:'Проверка',awaiting_payment:'Ожидает оплату',supplier_confirmation:'Подтверждение поставщика',processing:'В работе',partially_shipped:'Частично отправлен',shipped:'Отправлен',delivered:'Доставлен',not_collected:'Невыкуп',partially_returned:'Частичный возврат',returned:'Возвращён',problem:'Проблема',cancelled:'Отменён',
      unpaid:'Не оплачено',pending:'Оплата ожидается',paid:'Оплачено',failed:'Ошибка оплаты',partially_refunded:'Частичный возврат денег',refunded:'Деньги возвращены',
      not_started:'Не начата',preparing:'Подготовка',partially_delivered:'Частично доставлен',returning:'Возвращается',issue:'Проблема доставки',
      draft:'Черновик',awaiting_confirmation:'Ожидает подтверждения',confirmed:'Подтверждён',review:'На проверку',done:'Выполнено',dead:'Остановлено'
    };
    function h(value){return String(value==null?'':value).replace(/[&<>"']/g,function(char){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]})}
    function label(value){return labels[value]||value||'—'}
    function date(value){return value?new Intl.DateTimeFormat('ru-RU',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'—'}
    function money(value,currency){return value==null?'Неизвестно':new Intl.NumberFormat('ru-RU',{style:'currency',currency:currency||'RUB'}).format(Number(value)/100)}
    function pill(value){var kind=['delivered','paid','done','confirmed'].includes(value)?'ok':['problem','failed','dead','cancelled','returned','issue'].includes(value)?'bad':'warn';return '<span class="pill '+kind+'">'+h(label(value))+'</span>'}
    function toast(message){var el=document.getElementById('toast');el.textContent=message;el.classList.remove('hidden');setTimeout(function(){el.classList.add('hidden')},3500)}
    async function api(path,options){var opts=Object.assign({credentials:'same-origin'},options||{});if(opts.body&&typeof opts.body!=='string'){opts.headers=Object.assign({'content-type':'application/json'},opts.headers||{});opts.body=JSON.stringify(opts.body)}var response=await fetch(path,opts);var data=await response.json().catch(function(){return {ok:false,error:{message:'Некорректный ответ сервера.'}}});if(!response.ok){var error=new Error(data.error&&data.error.message||'Ошибка запроса');error.details=data.error&&data.error.details;error.status=response.status;throw error}return data}
    function showLogin(){document.getElementById('loginView').classList.remove('hidden');document.getElementById('appView').classList.add('hidden')}
    function showApp(){document.getElementById('loginView').classList.add('hidden');document.getElementById('appView').classList.remove('hidden');document.getElementById('accountName').textContent=state.user.name;document.getElementById('accountEmail').textContent=state.user.email;document.getElementById('topbarRole').textContent=label(state.user.role)}
    async function boot(){try{state.user=(await api('/api/auth/me')).user;showApp();await route('dashboard')}catch(error){showLogin()}}
    document.getElementById('loginForm').addEventListener('submit',async function(event){event.preventDefault();var error=document.getElementById('loginError');error.textContent='';try{state.user=(await api('/api/auth/login',{method:'POST',body:{email:document.getElementById('loginEmail').value,password:document.getElementById('loginPassword').value}})).user;showApp();await route('dashboard')}catch(failure){error.textContent=failure.message}});
    document.getElementById('logoutButton').addEventListener('click',async function(){await api('/api/auth/logout',{method:'POST'}).catch(function(){});state.user=null;showLogin()});
    document.getElementById('closeDialog').addEventListener('click',function(){document.getElementById('detailDialog').close()});
    document.querySelectorAll('[data-view]').forEach(function(button){button.addEventListener('click',function(){route(button.dataset.view)})});

    async function route(view){state.view=view;document.querySelectorAll('[data-view]').forEach(function(button){button.classList.toggle('active',button.dataset.view===view)});var titles={dashboard:'Обзор',orders:'Заказы',catalog:'Товары и поставщики',finance:'Финансы',automation:'Автоматизация'};document.getElementById('topbarTitle').textContent=titles[view];document.getElementById('content').innerHTML='<div class="empty">Загрузка…</div>';try{if(view==='dashboard')await renderDashboard();if(view==='orders')await renderOrders();if(view==='catalog')await renderCatalog();if(view==='finance')await renderFinance();if(view==='automation')await renderAutomation()}catch(error){document.getElementById('content').innerHTML='<div class="notice">'+h(error.message)+'</div>'}}

    async function renderDashboard(){state.dashboard=(await api('/api/admin/dashboard')).dashboard;var d=state.dashboard;document.getElementById('content').innerHTML='<div class="page-head"><div><h2>Что требует внимания</h2><p>Только рабочие показатели, без демонстрационных заказов.</p></div><button class="btn primary" id="goOrders">Открыть заказы</button></div><div class="grid stats"><div class="card stat"><span>Новые заказы</span><strong>'+d.orders.new+'</strong></div><div class="card stat attention"><span>Просроченные действия</span><strong>'+d.attention+'</strong></div><div class="card stat problem"><span>Проблемные заказы</span><strong>'+d.orders.problem+'</strong></div><div class="card stat"><span>Ошибки автоматизации</span><strong>'+d.automation.failed+'</strong></div><div class="card stat"><span>Устаревшие предложения</span><strong>'+d.staleOffers+'</strong></div></div><div class="split" style="margin-top:16px"><div class="card"><h3>Предварительная маржа</h3><div style="font-size:2rem;font-weight:900">'+money(d.finance.preliminaryKnownMinor,d.finance.currency)+'</div><p class="hint">Заказы с неизвестной маржой: '+d.finance.preliminaryUnknown+'. Суммы разных валют не объединяются без зафиксированного курса.</p></div><div class="card"><h3>Очередь проверки</h3><div style="font-size:2rem;font-weight:900">'+d.automation.review+'</div><p class="hint">Автоматические действия работают в режиме подготовки и требуют подтверждения менеджера.</p></div></div>';document.getElementById('goOrders').onclick=function(){route('orders')}}

    function orderTable(rows){if(!rows.length)return '<div class="empty">Заказов по выбранным условиям нет.</div>';return '<div class="table-wrap"><table class="table"><thead><tr><th>Заказ</th><th>Клиент</th><th>Статус</th><th>Оплата</th><th>Доставка</th><th>Ответственный</th><th>Следующее действие</th></tr></thead><tbody>'+rows.map(function(order){return '<tr data-order-id="'+h(order.id)+'"><td><span class="code">'+h(order.public_code)+'</span><span class="sub">'+date(order.created_at)+'</span></td><td>'+h(order.customer_name||'Без имени')+'<span class="sub">'+h(order.customer_contact)+'</span></td><td>'+pill(order.order_status)+'</td><td>'+pill(order.payment_status)+'</td><td>'+pill(order.delivery_status)+'</td><td>'+h(order.assigned_name||'Не назначен')+'</td><td>'+date(order.next_action_at)+'</td></tr>'}).join('')+'</tbody></table></div>'}
    async function renderOrders(){var data=await api('/api/admin/orders');state.orders=data.orders;document.getElementById('content').innerHTML='<div class="page-head"><div><h2>Заказы</h2><p>Поиск, статусы и ответственный в одном списке.</p></div></div><form id="orderFilters" class="toolbar"><input name="q" placeholder="Код, клиент или контакт"><select name="orderStatus"><option value="">Все статусы заказа</option>'+['new','checking','awaiting_payment','supplier_confirmation','processing','partially_shipped','shipped','delivered','problem','cancelled'].map(function(x){return '<option value="'+x+'">'+label(x)+'</option>'}).join('')+'</select><select name="paymentStatus"><option value="">Любая оплата</option>'+['unpaid','pending','paid','partially_refunded','refunded','failed'].map(function(x){return '<option value="'+x+'">'+label(x)+'</option>'}).join('')+'</select><select name="deliveryStatus"><option value="">Любая доставка</option>'+['not_started','preparing','partially_shipped','shipped','delivered','not_collected','returning','returned','issue'].map(function(x){return '<option value="'+x+'">'+label(x)+'</option>'}).join('')+'</select><button class="btn primary">Найти</button></form><div id="ordersTable">'+orderTable(state.orders)+'</div>';bindOrderRows();document.getElementById('orderFilters').onsubmit=async function(event){event.preventDefault();var query=new URLSearchParams(new FormData(event.currentTarget));state.orders=(await api('/api/admin/orders?'+query.toString())).orders;document.getElementById('ordersTable').innerHTML=orderTable(state.orders);bindOrderRows()}}
    function bindOrderRows(){document.querySelectorAll('[data-order-id]').forEach(function(row){row.onclick=function(){openOrder(row.dataset.orderId)}})}

    async function openOrder(orderId){var calls=[api('/api/admin/orders/'+encodeURIComponent(orderId)),api('/api/admin/suppliers'),api('/api/admin/offers')];if(state.user.role!=='finance')calls.push(api('/api/admin/staff').catch(function(){return {staff:[]}}));var result=await Promise.all(calls);var data=result[0];state.currentOrder=data;state.suppliers=result[1].suppliers;state.offers=result[2].offers;var staff=result[3]&&result[3].staff||[];var order=data.order;document.getElementById('dialogTitle').textContent=order.public_code;var statusControls='';if(['owner','manager'].includes(state.user.role)){statusControls='<form id="statusForm"><div class="form-row"><label class="field"><span>Заказ</span><select name="orderStatus">'+statusOptions(['new','checking','awaiting_payment','supplier_confirmation','processing','partially_shipped','shipped','delivered','not_collected','partially_returned','returned','problem','cancelled'],order.order_status)+'</select></label><label class="field"><span>Оплата</span><select name="paymentStatus">'+statusOptions(['unpaid','pending','paid','failed','partially_refunded','refunded','cancelled'],order.payment_status)+'</select></label><label class="field"><span>Доставка</span><select name="deliveryStatus">'+statusOptions(['not_started','preparing','partially_shipped','shipped','partially_delivered','delivered','not_collected','returning','returned','issue','cancelled'],order.delivery_status)+'</select></label></div><label class="field"><span>Ответственный</span><select name="assignedTo"><option value="">Не назначен</option>'+staff.map(function(person){return '<option value="'+h(person.id)+'" '+(person.id===order.assigned_to?'selected':'')+'>'+h(person.name)+' · '+label(person.role)+'</option>'}).join('')+'</select></label><button class="btn primary">Сохранить статусы</button></form>'}else{statusControls='<div class="kv"><div><span>Заказ</span><strong>'+label(order.order_status)+'</strong></div><div><span>Оплата</span><strong>'+label(order.payment_status)+'</strong></div><div><span>Доставка</span><strong>'+label(order.delivery_status)+'</strong></div></div>'}
      var supplierControls='';if(['owner','manager'].includes(state.user.role)){supplierControls='<form id="supplierOrderForm"><div class="form-row"><label class="field"><span>Поставщик</span><select name="supplierId" required><option value="">Выберите</option>'+state.suppliers.map(function(s){return '<option value="'+h(s.id)+'">'+h(s.name)+'</option>'}).join('')+'</select></label><label class="field"><span>Позиция клиента</span><select name="orderItemId" required>'+data.items.map(function(item){return '<option value="'+h(item.id)+'">'+h(item.title)+' · '+item.quantity+' шт.</option>'}).join('')+'</select></label><label class="field"><span>Предложение</span><select name="supplierOfferId" required><option value="">Выберите</option>'+state.offers.map(function(offer){return '<option value="'+h(offer.id)+'" data-supplier="'+h(offer.supplier_id)+'">'+h(offer.supplier_name)+' · '+h(offer.product_sku)+' · '+money(offer.purchase_price_minor,offer.currency)+'</option>'}).join('')+'</select></label></div><div class="form-row"><label class="field"><span>Количество</span><input name="quantity" type="number" value="1" min="1" required></label><label class="field"><span>Ожидаемая закупка, мин. ед.</span><input name="expectedPurchaseUnitMinor" type="number" placeholder="например 18800"></label></div><button class="btn primary">Подготовить заказ поставщику</button><p class="hint">Отправка поставщику не выполняется автоматически: создаётся черновик для проверки.</p></form>'}else{supplierControls='<p class="hint">Просмотр распределения доступен; изменение — владельцу и менеджеру.</p>'}
      var financeControls='';if(['owner','finance'].includes(state.user.role)){financeControls='<form id="financeForm"><div class="form-row"><label class="field"><span>Выручка, мин. ед.</span><input name="salesTotalMinor" type="number" value="'+h(order.sales_total_minor==null?'':order.sales_total_minor)+'"></label><label class="field"><span>Закупка (оценка)</span><input name="purchaseEstimateMinor" type="number" value="'+h(order.purchase_estimate_minor==null?'':order.purchase_estimate_minor)+'"></label><label class="field"><span>Доставка (оценка)</span><input name="deliveryCostEstimateMinor" type="number" value="'+h(order.delivery_cost_estimate_minor==null?'':order.delivery_cost_estimate_minor)+'"></label></div><div class="form-row"><label class="field"><span>Комиссии/расходы (оценка)</span><input name="commissionCostEstimateMinor" type="number" value="'+h(order.commission_cost_estimate_minor==null?'':order.commission_cost_estimate_minor)+'"></label><label class="field"><span>Скидка</span><input name="discountMinor" type="number" value="'+h(order.discount_minor||0)+'"></label><label class="field"><span>Все расходы учтены</span><select name="costsComplete"><option value="0" '+(!Number(order.costs_complete)?'selected':'')+'>Нет</option><option value="1" '+(Number(order.costs_complete)?'selected':'')+'>Да</option></select></label></div><button class="btn primary">Сохранить оценки</button></form><hr style="border:0;border-top:1px solid var(--line);margin:18px 0"><form id="movementForm"><div class="form-row"><label class="field"><span>Направление</span><select name="direction"><option value="in">Поступление</option><option value="out">Выплата</option></select></label><label class="field"><span>Категория</span><select name="category"><option value="revenue">Выручка</option><option value="purchase">Закупка</option><option value="delivery">Доставка</option><option value="fee">Комиссия</option><option value="refund">Возврат денег</option><option value="other">Другое</option></select></label><label class="field"><span>Начисление/факт</span><select name="status"><option value="planned">Начислено</option><option value="actual">Фактически</option></select></label></div><div class="form-row"><label class="field"><span>Сумма, мин. ед.</span><input name="amountMinor" type="number" min="0" required></label><label class="field"><span>Валюта</span><input name="currency" value="'+h(order.sale_currency)+'" required></label><label class="field"><span>Примечание</span><input name="note"></label></div><button class="btn">Записать движение денег</button></form>'}else{financeControls='<p class="hint">Изменение финансовых данных доступно владельцу и финансовому сотруднику.</p>'}
      document.getElementById('dialogBody').innerHTML='<div class="detail-grid"><div class="stack"><section class="card"><h3>Клиент</h3><div class="kv"><div><span>Имя</span><strong>'+h(order.customer_name||'Не указано')+'</strong></div><div><span>Контакт</span><strong>'+h(order.customer_contact||'Не указано')+'</strong></div><div><span>Город</span><strong>'+h(order.customer_city||'Не указано')+'</strong></div><div><span>Адрес</span><strong>'+h(order.customer_address||'Не указано')+'</strong></div></div></section><section class="card"><h3>Состав заказа</h3>'+data.items.map(function(item){return '<div class="item"><strong>'+h(item.title)+'</strong><span class="sub">'+item.quantity+' шт. · продажа '+money(item.sale_unit_minor,item.sale_currency)+' · закупка '+money(item.purchase_snapshot_minor,item.purchase_currency)+'</span></div>'}).join('')+'</section><section class="card"><h3>Статусы и ответственный</h3>'+statusControls+'</section><section class="card"><h3>Заказы поставщикам</h3>'+supplierOrderList(data.supplierOrders)+supplierControls+'</section></div><div class="stack"><section class="card"><h3>Финансовый результат</h3><div class="kv"><div><span>Начисленная выручка</span><strong>'+money(data.finance.accruedRevenueMinor,data.finance.currency)+'</strong></div><div><span>Предварительная маржа</span><strong>'+money(data.finance.preliminaryMarginMinor,data.finance.currency)+'</strong></div><div><span>Фактические поступления</span><strong>'+money(data.finance.actualInMinor,data.finance.currency)+'</strong></div><div><span>Фактические выплаты</span><strong>'+money(data.finance.actualOutMinor,data.finance.currency)+'</strong></div><div><span>Фактическая маржа</span><strong>'+money(data.finance.actualMarginMinor,data.finance.currency)+'</strong></div><div><span>Полнота расходов</span><strong>'+(data.finance.costsComplete?'Подтверждена':'Не подтверждена')+'</strong></div></div><p class="hint">Это маржа заказа, а не чистая прибыль: налоги и общие расходы компании здесь не учитываются автоматически.</p>'+financeControls+'</section><section class="card"><h3>История изменений</h3>'+data.events.map(function(event){return '<div class="event"><strong>'+h(label(event.event_type))+'</strong><small>'+date(event.created_at)+' · '+h(event.actor_name||'Система')+'</small></div>'}).join('')+'</section></div></div>';
      bindOrderDetail(orderId);document.getElementById('detailDialog').showModal()}
    function statusOptions(values,current){return values.map(function(value){return '<option value="'+value+'" '+(value===current?'selected':'')+'>'+h(label(value))+'</option>'}).join('')}
    function supplierOrderList(rows){if(!rows.length)return '<p class="hint">Пока нет заказов поставщикам.</p>';return rows.map(function(row){return '<div class="item"><strong>'+h(row.supplier_name)+' · '+pill(row.status)+'</strong><span class="sub">'+money(row.purchase_total_minor,row.purchase_currency)+' · '+row.items.length+' поз.</span></div>'}).join('')}
    function formObject(form){var result={};new FormData(form).forEach(function(value,key){result[key]=value});return result}
    function nullableInteger(value){return value===''?null:Number(value)}
    function bindOrderDetail(orderId){var statusForm=document.getElementById('statusForm');if(statusForm)statusForm.onsubmit=async function(event){event.preventDefault();var body=formObject(event.currentTarget);try{await api('/api/admin/orders/'+encodeURIComponent(orderId),{method:'PATCH',body:body});toast('Статусы сохранены');await openOrder(orderId)}catch(error){toast(error.message)}};var supplierForm=document.getElementById('supplierOrderForm');if(supplierForm)supplierForm.onsubmit=async function(event){event.preventDefault();var form=formObject(event.currentTarget);var body={supplierId:form.supplierId,items:[{orderItemId:form.orderItemId,supplierOfferId:form.supplierOfferId,quantity:Number(form.quantity),expectedPurchaseUnitMinor:nullableInteger(form.expectedPurchaseUnitMinor)}]};try{await api('/api/admin/orders/'+encodeURIComponent(orderId)+'/supplier-orders',{method:'POST',body:body});toast('Черновик заказа поставщику создан');await openOrder(orderId)}catch(error){var issues=error.details&&error.details.issues||[];toast(issues.length?issues.map(function(x){return x.message}).join(' '):error.message)}};var financeForm=document.getElementById('financeForm');if(financeForm)financeForm.onsubmit=async function(event){event.preventDefault();var form=formObject(event.currentTarget);var body={salesTotalMinor:nullableInteger(form.salesTotalMinor),purchaseEstimateMinor:nullableInteger(form.purchaseEstimateMinor),deliveryCostEstimateMinor:nullableInteger(form.deliveryCostEstimateMinor),commissionCostEstimateMinor:nullableInteger(form.commissionCostEstimateMinor),discountMinor:Number(form.discountMinor||0),costsComplete:form.costsComplete==='1'};try{await api('/api/admin/orders/'+encodeURIComponent(orderId)+'/finance',{method:'PATCH',body:body});toast('Финансовые оценки сохранены');await openOrder(orderId)}catch(error){toast(error.message)}};var movementForm=document.getElementById('movementForm');if(movementForm)movementForm.onsubmit=async function(event){event.preventDefault();var form=formObject(event.currentTarget);form.amountMinor=Number(form.amountMinor);try{await api('/api/admin/orders/'+encodeURIComponent(orderId)+'/money-movements',{method:'POST',body:form});toast('Движение денег записано');await openOrder(orderId)}catch(error){toast(error.message)}}}

    async function renderCatalog(){var result=await Promise.all([api('/api/admin/products'),api('/api/admin/suppliers')]);state.products=result[0].products;state.suppliers=result[1].suppliers;document.getElementById('content').innerHTML='<div class="page-head"><div><h2>Товары и предложения</h2><p>Артикулы ONYX, поставщики, цены, остатки и время обновления.</p></div></div><div class="split"><section class="card"><h3>Товары</h3>'+simpleProductTable(state.products)+'<form id="productForm" style="margin-top:18px"><div class="form-row"><label class="field"><span>Артикул</span><input name="sku" required></label><label class="field"><span>Название</span><input name="name" required></label><label class="field"><span>Категория</span><input name="category"></label></div><div class="form-row"><label class="field"><span>Цена продажи, мин. ед.</span><input name="salePriceMinor" type="number"></label><label class="field"><span>Валюта</span><select name="saleCurrency">'+['RUB','USD','UZS','KZT','TJS','KGS','BYN','EUR'].map(function(x){return '<option>'+x+'</option>'}).join('')+'</select></label><label class="field"><span>Мин. маржа, б.п.</span><input name="minMarginBps" type="number" placeholder="например 1500"></label></div><button class="btn primary">Добавить товар</button></form></section><section class="card"><h3>Поставщики</h3>'+simpleSupplierTable(state.suppliers)+'<form id="supplierForm" style="margin-top:18px"><div class="form-row"><label class="field"><span>Название</span><input name="name" required></label><label class="field"><span>Канал</span><select name="channel"><option value="wechat">WeChat</option><option value="csv">CSV</option><option value="manual">Вручную</option></select></label><label class="field"><span>Валюта</span><select name="defaultCurrency">'+['CNY','USD','RUB','EUR'].map(function(x){return '<option>'+x+'</option>'}).join('')+'</select></label></div><label class="field"><span>Контакт / примечание</span><input name="contact"></label><button class="btn primary">Добавить поставщика</button></form></section></div><section class="card" style="margin-top:16px"><h3>Импорт предложений поставщиков</h3><p class="notice">В первой версии поддержан проверяемый CSV. XLSX не маскируется под готовую интеграцию: его подключение требует образца реального файла поставщика.</p><label class="field"><span>CSV: supplier, product_sku, supplier_sku, purchase_price_minor, currency, stock_qty, stock_status, lead_time_days, stale_after_hours</span><textarea id="csvInput" class="csv" placeholder="supplier,product_sku,supplier_sku,purchase_price_minor,currency,stock_qty,stock_status,lead_time_days,stale_after_hours"></textarea></label><div class="actions"><button id="previewImport" class="btn">Проверить</button><button id="commitImport" class="btn primary" disabled>Импортировать</button></div><div id="importResult" class="hint" style="margin-top:12px"></div></section>';bindCatalog()}
    function simpleProductTable(rows){if(!rows.length)return '<p class="hint">Товаров пока нет.</p>';return '<div class="table-wrap"><table class="table" style="min-width:620px"><thead><tr><th>Артикул</th><th>Название</th><th>Цена</th><th>Предложения</th><th>Обновлено</th></tr></thead><tbody>'+rows.map(function(x){return '<tr><td>'+h(x.sku)+'</td><td>'+h(x.name)+'</td><td>'+money(x.sale_price_minor,x.sale_currency)+'</td><td>'+x.offer_count+'</td><td>'+date(x.last_offer_update)+'</td></tr>'}).join('')+'</tbody></table></div>'}
    function simpleSupplierTable(rows){if(!rows.length)return '<p class="hint">Поставщиков пока нет.</p>';return '<div class="table-wrap"><table class="table" style="min-width:540px"><thead><tr><th>Поставщик</th><th>Канал</th><th>Предложения</th><th>Проблемы</th></tr></thead><tbody>'+rows.map(function(x){return '<tr><td>'+h(x.name)+'</td><td>'+h(x.channel)+'</td><td>'+x.offer_count+'</td><td>'+x.attention_offers+'</td></tr>'}).join('')+'</tbody></table></div>'}
    function parseCsv(text){var lines=String(text).trim().split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];var delimiter=(lines[0].match(/;/g)||[]).length>(lines[0].match(/,/g)||[]).length?';':',';function row(line){var values=[],value='',quoted=false;for(var i=0;i<line.length;i++){var c=line[i];if(c==='"'&&line[i+1]==='"'){value+='"';i++}else if(c==='"'){quoted=!quoted}else if(c===delimiter&&!quoted){values.push(value.trim());value=''}else value+=c}values.push(value.trim());return values}var headers=row(lines[0]).map(function(x){return x.trim()});return lines.slice(1).map(function(line){var values=row(line),item={};headers.forEach(function(key,index){item[key]=values[index]||''});return item})}
    function bindCatalog(){var productForm=document.getElementById('productForm');productForm.onsubmit=async function(event){event.preventDefault();var body=formObject(event.currentTarget);body.salePriceMinor=nullableInteger(body.salePriceMinor);body.minMarginBps=nullableInteger(body.minMarginBps);try{await api('/api/admin/products',{method:'POST',body:body});toast('Товар добавлен');renderCatalog()}catch(error){toast(error.message)}};document.getElementById('supplierForm').onsubmit=async function(event){event.preventDefault();try{await api('/api/admin/suppliers',{method:'POST',body:formObject(event.currentTarget)});toast('Поставщик добавлен');renderCatalog()}catch(error){toast(error.message)}};var cachedRows=[];document.getElementById('previewImport').onclick=async function(){cachedRows=parseCsv(document.getElementById('csvInput').value);try{var result=await api('/api/admin/offers/import',{method:'POST',body:{rows:cachedRows,commit:false}});document.getElementById('importResult').textContent='Проверено строк: '+result.validRows+'. Ошибок нет.';document.getElementById('commitImport').disabled=false}catch(error){var errors=error.details&&error.details.errors||[];document.getElementById('importResult').textContent=errors.length?errors.map(function(x){return 'Строка '+x.line+': '+x.message}).join(' '):error.message;document.getElementById('commitImport').disabled=true}};document.getElementById('commitImport').onclick=async function(){try{var result=await api('/api/admin/offers/import',{method:'POST',body:{rows:cachedRows,commit:true}});toast('Импортировано предложений: '+result.imported);renderCatalog()}catch(error){toast(error.message)}}}

    async function renderFinance(){var orders=(await api('/api/admin/orders')).orders;document.getElementById('content').innerHTML='<div class="page-head"><div><h2>Финансы</h2><p>Начисления и движения денег не смешиваются; неизвестные расходы остаются неизвестными.</p></div></div>'+orderTable(orders);bindOrderRows()}
    async function renderAutomation(){var result=await Promise.all([api('/api/admin/jobs'),api('/api/admin/rules')]);state.jobs=result[0].jobs;state.rules=result[1].rules;var rulesHtml='<section class="card" style="margin-bottom:16px"><h3>Правила</h3>'+(state.rules.length?state.rules.map(function(rule){var ruleState='<span class="pill '+(rule.enabled?'ok':'warn')+'">'+(rule.enabled?'Включено':'Остановлено')+'</span>';return '<div class="item"><strong>'+h(rule.name)+' · '+ruleState+'</strong><span class="sub">'+h(rule.trigger_event)+' → '+h(rule.action_type)+' → режим '+h(rule.mode)+' → ответственный '+h(label(rule.responsible_role))+'</span>'+(state.user.role==='owner'?'<button class="btn" style="margin-top:9px" data-toggle-rule="'+h(rule.id)+'" data-enabled="'+rule.enabled+'">'+(rule.enabled?'Остановить':'Включить')+'</button>':'')+'</div>'}).join(''):'<p class="hint">Правил пока нет.</p>')+'</section>';document.getElementById('content').innerHTML='<div class="page-head"><div><h2>Очередь автоматизации</h2><p>Первый режим — подготовка действий на проверку. Реальные отправки отключены.</p></div></div>'+rulesHtml+(state.jobs.length?'<div class="table-wrap"><table class="table"><thead><tr><th>Операция</th><th>Заказ</th><th>Статус</th><th>Попытки</th><th>Ошибка</th><th></th></tr></thead><tbody>'+state.jobs.map(function(job){return '<tr><td>'+h(job.action_type)+'</td><td>'+h(job.public_code||'—')+'</td><td>'+pill(job.status)+'</td><td>'+job.attempts+' / '+job.max_attempts+'</td><td>'+h(job.last_error_message||'—')+'</td><td>'+(['failed','dead'].includes(job.status)&&['owner','manager'].includes(state.user.role)?'<button class="btn" data-retry-job="'+h(job.id)+'">Повторить</button>':'—')+'</td></tr>'}).join('')+'</tbody></table></div>':'<div class="empty">Очередь проблемных операций пуста.</div>');document.querySelectorAll('[data-retry-job]').forEach(function(button){button.onclick=async function(){try{await api('/api/admin/jobs/'+encodeURIComponent(button.dataset.retryJob)+'/retry',{method:'POST'});toast('Операция возвращена в очередь');renderAutomation()}catch(error){toast(error.message)}}});document.querySelectorAll('[data-toggle-rule]').forEach(function(button){button.onclick=async function(){try{await api('/api/admin/rules/'+encodeURIComponent(button.dataset.toggleRule),{method:'PATCH',body:{enabled:button.dataset.enabled!=='1'}});toast('Правило обновлено');renderAutomation()}catch(error){toast(error.message)}}})}
    boot();
  </script>
</body>
</html>`;
}
